/**
 * Local fixture data for the Vendor Mail Tracker.
 *
 * These are static mocks used during isolated development. No real vendor
 * data, PII, or live API calls are used here. Replace with service calls
 * in a future integration issue.
 */

import type { Vendor, VendorThread } from "./types";

export const FIXTURE_VENDORS: Vendor[] = [
  {
    id: "v-001",
    name: "Orbit Cloud",
    domain: "orbitcloud.io",
    contactEmail: "billing@orbitcloud.io",
    category: "infrastructure",
    status: "active",
    contractStart: "2024-01-15",
    contractEnd: "2026-01-14",
    monthlySpendCents: 480000,
    address: "1 Cloud Ave, San Francisco, CA 94107",
    threadCount: 4,
    notes: "Primary hosting provider. Auto-renews unless cancelled 90 days prior.",
  },
  {
    id: "v-002",
    name: "Keystroke Analytics",
    domain: "keystroke.co",
    contactEmail: "team@keystroke.co",
    category: "software",
    status: "active",
    contractStart: "2024-06-01",
    contractEnd: "2025-05-31",
    monthlySpendCents: 99900,
    address: "42 Insight Blvd, Austin, TX 78701",
    threadCount: 2,
    notes: "Usage-based billing. Check dashboard monthly.",
  },
  {
    id: "v-003",
    name: "Nexbridge Legal",
    domain: "nexbridge.law",
    contactEmail: "contracts@nexbridge.law",
    category: "legal",
    status: "pending",
    contractStart: "2025-07-01",
    contractEnd: null,
    monthlySpendCents: 0,
    address: "300 Law Plaza, New York, NY 10007",
    threadCount: 1,
    notes: "Awaiting NDA and MSA signatures before work begins.",
  },
  {
    id: "v-004",
    name: "Relay Relay Logistics",
    domain: "relayrelay.com",
    contactEmail: "ops@relayrelay.com",
    category: "logistics",
    status: "paused",
    contractStart: "2023-03-10",
    contractEnd: "2025-03-09",
    monthlySpendCents: 220000,
    address: "99 Freight St, Chicago, IL 60601",
    threadCount: 3,
    notes: "Contract expired. Renewal negotiation in progress.",
  },
  {
    id: "v-005",
    name: "Cardamom Finance",
    domain: "cardamom.finance",
    contactEmail: "ap@cardamom.finance",
    category: "finance",
    status: "active",
    contractStart: "2023-11-01",
    contractEnd: null,
    monthlySpendCents: 150000,
    address: "7 Treasury Lane, Boston, MA 02110",
    threadCount: 6,
    notes: "Handles AP processing. SLA: 48h response on payment queries.",
  },
  {
    id: "v-006",
    name: "Fieldwork HR",
    domain: "fieldworkhr.io",
    contactEmail: "support@fieldworkhr.io",
    category: "hr",
    status: "terminated",
    contractStart: "2022-04-01",
    contractEnd: "2024-12-31",
    monthlySpendCents: 0,
    address: "15 People St, Seattle, WA 98101",
    threadCount: 0,
    notes: "Contract ended. Keep records for audit trail.",
  },
];

export const FIXTURE_THREADS: VendorThread[] = [
  // Orbit Cloud threads
  {
    id: "t-001",
    vendorId: "v-001",
    subject: "Bandwidth overage charges — June invoice",
    lastMessageAt: "2025-06-17T09:22:00Z",
    followUpAt: "2025-06-20T09:00:00Z",
    status: "awaiting-reply",
    priority: "high",
    messageCount: 5,
    excerpt: "We've reviewed the overage and believe the spike was due to the migration window...",
    unread: true,
    tags: ["billing", "invoice"],
  },
  {
    id: "t-002",
    vendorId: "v-001",
    subject: "SOC 2 Type II report request",
    lastMessageAt: "2025-06-10T14:05:00Z",
    followUpAt: null,
    status: "open",
    priority: "medium",
    messageCount: 2,
    excerpt: "Please find the requested SOC 2 report attached for your compliance review.",
    unread: false,
    tags: ["compliance", "security"],
  },
  {
    id: "t-003",
    vendorId: "v-001",
    subject: "Uptime SLA credit — Q2",
    lastMessageAt: "2025-06-01T11:30:00Z",
    followUpAt: null,
    status: "resolved",
    priority: "low",
    messageCount: 8,
    excerpt: "Credit of $480 has been applied to your next billing cycle.",
    unread: false,
    tags: ["sla", "billing"],
  },
  {
    id: "t-004",
    vendorId: "v-001",
    subject: "Emergency escalation: production outage 06-15",
    lastMessageAt: "2025-06-15T03:44:00Z",
    followUpAt: "2025-06-21T09:00:00Z",
    status: "escalated",
    priority: "critical",
    messageCount: 14,
    excerpt: "Post-incident report received. Root cause identified as config drift in region us-east-2.",
    unread: true,
    tags: ["incident", "escalation", "production"],
  },
  // Keystroke threads
  {
    id: "t-005",
    vendorId: "v-002",
    subject: "API rate-limit increase request",
    lastMessageAt: "2025-06-12T16:55:00Z",
    followUpAt: null,
    status: "resolved",
    priority: "medium",
    messageCount: 3,
    excerpt: "Your plan has been updated to 500 req/min. Changes effective immediately.",
    unread: false,
    tags: ["api", "plan"],
  },
  {
    id: "t-006",
    vendorId: "v-002",
    subject: "GDPR data processing addendum",
    lastMessageAt: "2025-06-16T08:00:00Z",
    followUpAt: "2025-06-25T08:00:00Z",
    status: "awaiting-reply",
    priority: "high",
    messageCount: 1,
    excerpt: "Awaiting legal team's sign-off on the updated DPA before countersigning.",
    unread: true,
    tags: ["legal", "gdpr", "compliance"],
  },
  // Nexbridge Legal threads
  {
    id: "t-007",
    vendorId: "v-003",
    subject: "MSA redlines — version 3",
    lastMessageAt: "2025-06-18T07:15:00Z",
    followUpAt: "2025-06-19T17:00:00Z",
    status: "flagged",
    priority: "critical",
    messageCount: 6,
    excerpt: "Clause 8.3 on liability limitation remains unresolved. Requesting call this week.",
    unread: true,
    tags: ["legal", "contract", "msa"],
  },
  // Relay Relay threads
  {
    id: "t-008",
    vendorId: "v-004",
    subject: "Contract renewal terms",
    lastMessageAt: "2025-06-05T12:00:00Z",
    followUpAt: "2025-06-30T09:00:00Z",
    status: "open",
    priority: "medium",
    messageCount: 4,
    excerpt: "Happy to discuss new volume tiers. Proposed 10% discount for 24-month commitment.",
    unread: false,
    tags: ["renewal", "contract"],
  },
  {
    id: "t-009",
    vendorId: "v-004",
    subject: "Final invoice reconciliation",
    lastMessageAt: "2025-05-28T09:45:00Z",
    followUpAt: null,
    status: "resolved",
    priority: "low",
    messageCount: 7,
    excerpt: "All charges reconciled. Final balance of $0 confirmed.",
    unread: false,
    tags: ["billing", "invoice"],
  },
  {
    id: "t-010",
    vendorId: "v-004",
    subject: "Data export request post-offboarding",
    lastMessageAt: "2025-06-08T14:20:00Z",
    followUpAt: "2025-06-22T09:00:00Z",
    status: "awaiting-reply",
    priority: "medium",
    messageCount: 2,
    excerpt: "Export will be available via secure link. Expected delivery within 5 business days.",
    unread: false,
    tags: ["offboarding", "data"],
  },
  // Cardamom Finance threads
  {
    id: "t-011",
    vendorId: "v-005",
    subject: "ACH setup for new accounts payable",
    lastMessageAt: "2025-06-14T10:10:00Z",
    followUpAt: null,
    status: "resolved",
    priority: "medium",
    messageCount: 5,
    excerpt: "ACH routing confirmed. First payment scheduled for July 1.",
    unread: false,
    tags: ["payment", "setup"],
  },
  {
    id: "t-012",
    vendorId: "v-005",
    subject: "Failed payment — INV-2025-044",
    lastMessageAt: "2025-06-17T13:00:00Z",
    followUpAt: "2025-06-19T09:00:00Z",
    status: "escalated",
    priority: "critical",
    messageCount: 3,
    excerpt: "Insufficient funds error on June 15. Retry scheduled for June 18 with backup account.",
    unread: true,
    tags: ["payment", "escalation", "billing"],
  },
  {
    id: "t-013",
    vendorId: "v-005",
    subject: "Q3 budget forecast alignment",
    lastMessageAt: "2025-06-03T15:30:00Z",
    followUpAt: null,
    status: "open",
    priority: "low",
    messageCount: 2,
    excerpt: "Attached updated cost projections based on current run rate.",
    unread: false,
    tags: ["budget", "forecast"],
  },
  {
    id: "t-014",
    vendorId: "v-005",
    subject: "Expense report audit — May 2025",
    lastMessageAt: "2025-06-09T11:20:00Z",
    followUpAt: null,
    status: "resolved",
    priority: "low",
    messageCount: 4,
    excerpt: "Audit complete. No discrepancies found in the May report.",
    unread: false,
    tags: ["audit", "expenses"],
  },
  {
    id: "t-015",
    vendorId: "v-005",
    subject: "New banking details notification",
    lastMessageAt: "2025-06-11T09:00:00Z",
    followUpAt: "2025-06-20T09:00:00Z",
    status: "flagged",
    priority: "high",
    messageCount: 1,
    excerpt: "Please verify this change through our secure portal before updating records.",
    unread: true,
    tags: ["banking", "security", "flagged"],
  },
  {
    id: "t-016",
    vendorId: "v-005",
    subject: "Annual contract review meeting prep",
    lastMessageAt: "2025-05-30T16:00:00Z",
    followUpAt: null,
    status: "resolved",
    priority: "medium",
    messageCount: 6,
    excerpt: "Meeting notes and action items shared via secure link.",
    unread: false,
    tags: ["contract", "review"],
  },
];

/** Summary stats derived from fixture data. */
export function getFixtureStats(threads: VendorThread[]) {
  const total = threads.length;
  const unread = threads.filter((t) => t.unread).length;
  const escalated = threads.filter((t) => t.status === "escalated").length;
  const awaitingReply = threads.filter((t) => t.status === "awaiting-reply").length;
  const critical = threads.filter((t) => t.priority === "critical").length;
  const dueForFollowUp = threads.filter((t) => {
    if (!t.followUpAt) return false;
    return new Date(t.followUpAt) <= new Date(Date.now() + 2 * 24 * 60 * 60 * 1000);
  }).length;

  return { total, unread, escalated, awaitingReply, critical, dueForFollowUp };
}
