/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiV1ProtocolRouteImport } from './routes/api/v1/protocol'
import { Route as ApiV1HealthRouteImport } from './routes/api/v1/health'
import { Route as ApiV1PostageIndexRouteImport } from './routes/api/v1/postage/index'
import { Route as ApiV1PostageQuoteRouteImport } from './routes/api/v1/postage/quote'
import { Route as ApiV1PostageMessageIdRouteImport } from './routes/api/v1/postage/$messageId'
import { Route as ApiV1PoliciesEvaluateRouteImport } from './routes/api/v1/policies/evaluate'
import { Route as ApiV1PoliciesOwnerRouteImport } from './routes/api/v1/policies/$owner'
import { Route as ApiV1PostageMessageIdSettleRouteImport } from './routes/api/v1/postage/$messageId/settle'
import { Route as ApiV1PoliciesOwnerSendersSenderRouteImport } from './routes/api/v1/policies/$owner/senders/$sender'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ProtocolRoute = ApiV1ProtocolRouteImport.update({
  id: '/api/v1/protocol',
  path: '/api/v1/protocol',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HealthRoute = ApiV1HealthRouteImport.update({
  id: '/api/v1/health',
  path: '/api/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PostageIndexRoute = ApiV1PostageIndexRouteImport.update({
  id: '/api/v1/postage/',
  path: '/api/v1/postage/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PostageQuoteRoute = ApiV1PostageQuoteRouteImport.update({
  id: '/api/v1/postage/quote',
  path: '/api/v1/postage/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PostageMessageIdRoute = ApiV1PostageMessageIdRouteImport.update({
  id: '/api/v1/postage/$messageId',
  path: '/api/v1/postage/$messageId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PoliciesEvaluateRoute = ApiV1PoliciesEvaluateRouteImport.update({
  id: '/api/v1/policies/evaluate',
  path: '/api/v1/policies/evaluate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PoliciesOwnerRoute = ApiV1PoliciesOwnerRouteImport.update({
  id: '/api/v1/policies/$owner',
  path: '/api/v1/policies/$owner',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PostageMessageIdSettleRoute =
  ApiV1PostageMessageIdSettleRouteImport.update({
    id: '/settle',
    path: '/settle',
    getParentRoute: () => ApiV1PostageMessageIdRoute,
  } as any)
const ApiV1PoliciesOwnerSendersSenderRoute =
  ApiV1PoliciesOwnerSendersSenderRouteImport.update({
    id: '/senders/$sender',
    path: '/senders/$sender',
    getParentRoute: () => ApiV1PoliciesOwnerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/protocol': typeof ApiV1ProtocolRoute
  '/api/v1/policies/$owner': typeof ApiV1PoliciesOwnerRouteWithChildren
  '/api/v1/policies/evaluate': typeof ApiV1PoliciesEvaluateRoute
  '/api/v1/postage/$messageId': typeof ApiV1PostageMessageIdRouteWithChildren
  '/api/v1/postage/quote': typeof ApiV1PostageQuoteRoute
  '/api/v1/postage/': typeof ApiV1PostageIndexRoute
  '/api/v1/postage/$messageId/settle': typeof ApiV1PostageMessageIdSettleRoute
  '/api/v1/policies/$owner/senders/$sender': typeof ApiV1PoliciesOwnerSendersSenderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/protocol': typeof ApiV1ProtocolRoute
  '/api/v1/policies/$owner': typeof ApiV1PoliciesOwnerRouteWithChildren
  '/api/v1/policies/evaluate': typeof ApiV1PoliciesEvaluateRoute
  '/api/v1/postage/$messageId': typeof ApiV1PostageMessageIdRouteWithChildren
  '/api/v1/postage/quote': typeof ApiV1PostageQuoteRoute
  '/api/v1/postage': typeof ApiV1PostageIndexRoute
  '/api/v1/postage/$messageId/settle': typeof ApiV1PostageMessageIdSettleRoute
  '/api/v1/policies/$owner/senders/$sender': typeof ApiV1PoliciesOwnerSendersSenderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/protocol': typeof ApiV1ProtocolRoute
  '/api/v1/policies/$owner': typeof ApiV1PoliciesOwnerRouteWithChildren
  '/api/v1/policies/evaluate': typeof ApiV1PoliciesEvaluateRoute
  '/api/v1/postage/$messageId': typeof ApiV1PostageMessageIdRouteWithChildren
  '/api/v1/postage/quote': typeof ApiV1PostageQuoteRoute
  '/api/v1/postage/': typeof ApiV1PostageIndexRoute
  '/api/v1/postage/$messageId/settle': typeof ApiV1PostageMessageIdSettleRoute
  '/api/v1/policies/$owner/senders/$sender': typeof ApiV1PoliciesOwnerSendersSenderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/v1/health'
    | '/api/v1/protocol'
    | '/api/v1/policies/$owner'
    | '/api/v1/policies/evaluate'
    | '/api/v1/postage/$messageId'
    | '/api/v1/postage/quote'
    | '/api/v1/postage/'
    | '/api/v1/postage/$messageId/settle'
    | '/api/v1/policies/$owner/senders/$sender'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/v1/health'
    | '/api/v1/protocol'
    | '/api/v1/policies/$owner'
    | '/api/v1/policies/evaluate'
    | '/api/v1/postage/$messageId'
    | '/api/v1/postage/quote'
    | '/api/v1/postage'
    | '/api/v1/postage/$messageId/settle'
    | '/api/v1/policies/$owner/senders/$sender'
  id:
    | '__root__'
    | '/'
    | '/api/v1/health'
    | '/api/v1/protocol'
    | '/api/v1/policies/$owner'
    | '/api/v1/policies/evaluate'
    | '/api/v1/postage/$messageId'
    | '/api/v1/postage/quote'
    | '/api/v1/postage/'
    | '/api/v1/postage/$messageId/settle'
    | '/api/v1/policies/$owner/senders/$sender'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiV1HealthRoute: typeof ApiV1HealthRoute
  ApiV1ProtocolRoute: typeof ApiV1ProtocolRoute
  ApiV1PoliciesOwnerRoute: typeof ApiV1PoliciesOwnerRouteWithChildren
  ApiV1PoliciesEvaluateRoute: typeof ApiV1PoliciesEvaluateRoute
  ApiV1PostageMessageIdRoute: typeof ApiV1PostageMessageIdRouteWithChildren
  ApiV1PostageQuoteRoute: typeof ApiV1PostageQuoteRoute
  ApiV1PostageIndexRoute: typeof ApiV1PostageIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/protocol': {
      id: '/api/v1/protocol'
      path: '/api/v1/protocol'
      fullPath: '/api/v1/protocol'
      preLoaderRoute: typeof ApiV1ProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/health': {
      id: '/api/v1/health'
      path: '/api/v1/health'
      fullPath: '/api/v1/health'
      preLoaderRoute: typeof ApiV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/postage/': {
      id: '/api/v1/postage/'
      path: '/api/v1/postage'
      fullPath: '/api/v1/postage/'
      preLoaderRoute: typeof ApiV1PostageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/postage/quote': {
      id: '/api/v1/postage/quote'
      path: '/api/v1/postage/quote'
      fullPath: '/api/v1/postage/quote'
      preLoaderRoute: typeof ApiV1PostageQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/postage/$messageId': {
      id: '/api/v1/postage/$messageId'
      path: '/api/v1/postage/$messageId'
      fullPath: '/api/v1/postage/$messageId'
      preLoaderRoute: typeof ApiV1PostageMessageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/policies/evaluate': {
      id: '/api/v1/policies/evaluate'
      path: '/api/v1/policies/evaluate'
      fullPath: '/api/v1/policies/evaluate'
      preLoaderRoute: typeof ApiV1PoliciesEvaluateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/policies/$owner': {
      id: '/api/v1/policies/$owner'
      path: '/api/v1/policies/$owner'
      fullPath: '/api/v1/policies/$owner'
      preLoaderRoute: typeof ApiV1PoliciesOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/postage/$messageId/settle': {
      id: '/api/v1/postage/$messageId/settle'
      path: '/settle'
      fullPath: '/api/v1/postage/$messageId/settle'
      preLoaderRoute: typeof ApiV1PostageMessageIdSettleRouteImport
      parentRoute: typeof ApiV1PostageMessageIdRoute
    }
    '/api/v1/policies/$owner/senders/$sender': {
      id: '/api/v1/policies/$owner/senders/$sender'
      path: '/senders/$sender'
      fullPath: '/api/v1/policies/$owner/senders/$sender'
      preLoaderRoute: typeof ApiV1PoliciesOwnerSendersSenderRouteImport
      parentRoute: typeof ApiV1PoliciesOwnerRoute
    }
  }
}

interface ApiV1PoliciesOwnerRouteChildren {
  ApiV1PoliciesOwnerSendersSenderRoute: typeof ApiV1PoliciesOwnerSendersSenderRoute
}

const ApiV1PoliciesOwnerRouteChildren: ApiV1PoliciesOwnerRouteChildren = {
  ApiV1PoliciesOwnerSendersSenderRoute: ApiV1PoliciesOwnerSendersSenderRoute,
}

const ApiV1PoliciesOwnerRouteWithChildren =
  ApiV1PoliciesOwnerRoute._addFileChildren(ApiV1PoliciesOwnerRouteChildren)

interface ApiV1PostageMessageIdRouteChildren {
  ApiV1PostageMessageIdSettleRoute: typeof ApiV1PostageMessageIdSettleRoute
}

const ApiV1PostageMessageIdRouteChildren: ApiV1PostageMessageIdRouteChildren = {
  ApiV1PostageMessageIdSettleRoute: ApiV1PostageMessageIdSettleRoute,
}

const ApiV1PostageMessageIdRouteWithChildren =
  ApiV1PostageMessageIdRoute._addFileChildren(
    ApiV1PostageMessageIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiV1HealthRoute: ApiV1HealthRoute,
  ApiV1ProtocolRoute: ApiV1ProtocolRoute,
  ApiV1PoliciesOwnerRoute: ApiV1PoliciesOwnerRouteWithChildren,
  ApiV1PoliciesEvaluateRoute: ApiV1PoliciesEvaluateRoute,
  ApiV1PostageMessageIdRoute: ApiV1PostageMessageIdRouteWithChildren,
  ApiV1PostageQuoteRoute: ApiV1PostageQuoteRoute,
  ApiV1PostageIndexRoute: ApiV1PostageIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
